services:
  api:
    image: oniro-plane-api:planning-v1
  worker:
    image: oniro-plane-api:planning-v1
  beat-worker:
    image: oniro-plane-api:planning-v1
  migrator:
    image: oniro-plane-api:planning-v1
  web:
    image: oniro-plane-web:planning-v1
