"""Transfer this public-code-only add-on to the authorized staging directory."""
import io
import subprocess
import sys
import tarfile
from pathlib import Path

DEST = '/home/plane/staging/oniro-planning-20260914'
SSH = ['tailscale', 'ssh', 'plane@plane-aziendaa']

if sys.argv[1] == 'upload':
    root = Path(__file__).resolve().parent
    stream = io.BytesIO()
    with tarfile.open(fileobj=stream, mode='w:gz') as archive:
        for path in root.rglob('*'):
            if path.is_file() and '__pycache__' not in path.parts and path.suffix != '.pyc':
                archive.add(path, arcname=str(path.relative_to(root)))
    command = f'mkdir -p {DEST} && tar -xzf - -C {DEST}'
    subprocess.run(SSH + [command], input=stream.getvalue(), check=True)
    print('Uploaded planning source to isolated staging directory')
elif sys.argv[1] == 'run':
    subprocess.run(SSH + [sys.argv[2]], check=True)
elif sys.argv[1] == 'script':
    script = Path(sys.argv[2]).read_text(encoding='utf-8').replace('\r\n', '\n')
    subprocess.run(SSH + ['bash -s'], input=script.encode(), check=True)
elif sys.argv[1] == 'migration':
    target = Path(__file__).resolve().parent / 'oniro_planning/migrations/0001_initial.py'
    data = subprocess.check_output(SSH + [f'cat {DEST}/oniro_planning/migrations/0001_initial.py'])
    if not data.startswith(b'# Generated by Django'):
        raise RuntimeError('Unexpected migration output')
    target.write_bytes(data)
    print('Saved generated migration')
else:
    raise SystemExit('Use upload, run, or migration')
