# Generated by Django 4.2.30 on 2026-09-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0131_v137e_canonical_workflow_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.project')),
            ],
        ),
        migrations.CreateModel(
            name='PlanSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('minutes', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=1)),
                ('outcome', models.CharField(max_length=1000)),
                ('status', models.CharField(default='planned', max_length=16)),
                ('blocker', models.CharField(blank=True, max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_created', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.issue')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'ordering': ['day', 'person_id', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='oniro_planning.planslot')),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('minutes', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='planslot',
            index=models.Index(fields=['workspace', 'day'], name='oniro_plann_workspa_b69a46_idx'),
        ),
        migrations.AddConstraint(
            model_name='planslot',
            constraint=models.CheckConstraint(check=models.Q(('minutes__gte', 1), ('minutes__lte', 1440)), name='planning_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='planslot',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'rescheduled']), _negated=True), fields=('workspace', 'issue', 'person', 'day'), name='planning_unique_daily_commitment'),
        ),
        migrations.AddConstraint(
            model_name='capacity',
            constraint=models.UniqueConstraint(fields=('workspace', 'person', 'day'), name='planning_unique_capacity'),
        ),
        migrations.AddConstraint(
            model_name='capacity',
            constraint=models.CheckConstraint(check=models.Q(('minutes__lte', 1440)), name='planning_capacity_range'),
        ),
    ]
