'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const newId = () => crypto.randomUUID ? crypto.randomUUID() : '10000000-1000-4000-8000-100000000000'.replace(/[018]/g, c => (Number(c) ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> Number(c) / 4).toString(16));
  const slug = decodeURIComponent(location.pathname.split('/').filter(Boolean)[0] || '');
  const base = '/api/workspaces/' + encodeURIComponent(slug) + '/planning/';
  const statusNames = {planned:'Da fare',working:'In corso',blocked:'In attesa',done:'Fatto oggi',cancelled:'Annullato',rescheduled:'Ripianificato'};
  const priorityNames = {urgent:'Urgente',high:'Alta',medium:'Media',low:'Bassa',none:'Non definita'};
  const state = {view:'team',boot:null,slots:[],capacities:[],day:'',carry:[],detail:null,requestId:0,issues:[],nextOffset:null,createId:null,reschedule:null,capacityPerson:null,commentCursor:null};
  const hours = n => (n/60).toLocaleString('it-IT',{maximumFractionDigits:2})+' h';
  const displayDate = d => new Date(d+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short'});
  const shift = (day,n) => {const d=new Date(day+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
  function range(){const day=state.day;const start=state.view==='week'?shift(day,-((new Date(day+'T12:00:00').getDay()+6)%7)):day;return {from:start,to:state.view==='week'?shift(start,6):start};}
  function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
  const personName=id=>state.boot.members.find(m=>m.id===id)?.name||'Persona non più attiva';
  function clearError(){$('error').hidden=true;$('error').textContent='';}
  function errorText(err){return err.message||'Operazione non riuscita';}
  function showError(err){$('error').textContent=errorText(err);$('error').hidden=false;}
  async function api(path,options={}){
    const headers={Accept:'application/json',...options.headers};
    if(options.body){headers['Content-Type']='application/json';headers['X-CSRFToken']=state.boot?.csrf_token||'';}
    let response;
    try{response=await fetch(path.startsWith('/')?path:base+path,{credentials:'same-origin',...options,headers});}
    catch{throw new Error(options.method&&options.method!=='GET'?'Connessione interrotta: la scrittura potrebbe essere riuscita. Aggiorna e verifica prima di riprovare.':'Connessione al server non disponibile.');}
    let data;try{data=await response.json();}catch{throw new Error('Risposta non valida dal server. Verifica l’accesso a Plane.');}
    if(!response.ok){const details=typeof data==='string'?data:Object.values(data).flat().join(' ');throw new Error(response.status===409?'Il piano è cambiato da un’altra sessione. Chiudi, aggiorna e riapri prima di salvare.':response.status===403?'Accesso non consentito. Accedi a Plane e verifica i permessi.':response.status===429?'Troppe richieste: attendi qualche istante e aggiorna.':details||`Errore ${response.status}`);}
    return data;
  }
  async function all(path,params){const out=[];let offset=0;for(let page=0;page<100;page++){const data=await api(path+'?'+new URLSearchParams({...params,offset,limit:200}));out.push(...data.results);if(data.next_offset==null)return out;if(data.next_offset<=offset)throw new Error('Paginazione non valida');offset=data.next_offset;}throw new Error('Troppi risultati: restringi l’intervallo.');}
  async function refresh(){
    const id=++state.requestId;clearError();$('loading').hidden=false;
    try{const r=range();const [slots,capacities]=await Promise.all([all('slots/',r),api('capacities/?'+new URLSearchParams(r))]);if(id!==state.requestId)return;state.slots=slots;state.capacities=capacities.results;$('notice').textContent='Aggiornato alle '+new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});render();if($('carryover').open)await loadCarry();}
    catch(e){showError(e);}finally{if(id===state.requestId)$('loading').hidden=true;}
  }
  function capacity(person,day){return state.capacities.find(c=>c.person_id===person&&c.day===day);}
  function daySlots(person,day){return state.slots.filter(s=>s.person_id===person&&s.day===day&&!['cancelled','rescheduled'].includes(s.status)).sort((a,b)=>a.position-b.position||a.id.localeCompare(b.id));}
  function capacityLabel(person,day,slots){const planned=slots.reduce((n,s)=>n+s.minutes,0),c=capacity(person,day);const label=el('span',hours(planned)+' pianificate'+(c?' / '+hours(c.minutes)+' disponibili':' · disponibilità da indicare'),c&&planned>c.minutes?'overload':'muted');return label;}
  function taskCard(slot,compact=false){const b=el('button',undefined,'task '+(slot.issue.priority==='urgent'?'urgent ':'')+(slot.status==='done'?'done ':'')+(compact?'week-task':''));b.type='button';b.append(el('span',slot.position+'. '+(priorityNames[slot.issue.priority]||'Non definita')+' · '+hours(slot.minutes),'rank'),el('span',slot.issue.project+' · '+slot.issue.identifier,'meta'),el('strong',slot.issue.name),el('span',statusNames[slot.status]||slot.status,'meta'));if(slot.issue.target_date)b.append(el('span','Scade '+displayDate(slot.issue.target_date),'meta'));if(slot.status==='blocked')b.append(el('span',slot.blocker,'blocked'));if(!compact)b.append(el('span',slot.outcome,'meta'));b.addEventListener('click',()=>openDetail(slot));return b;}
  function render(){
    document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===state.view)));
    const board=$('board');board.replaceChildren();
    const members=state.view==='me'?state.boot.members.filter(m=>m.id===state.boot.user_id):state.boot.members;
    if(state.view==='week'){
      const wrap=el('div',undefined,'week-wrap'),table=el('table'),head=el('tr');head.append(el('th','Persona'));const r=range(),days=Array.from({length:7},(_,i)=>shift(r.from,i));for(const d of days)head.append(el('th',new Date(d+'T12:00:00').toLocaleDateString('it-IT',{weekday:'short',day:'numeric'})));const thead=el('thead');thead.append(head);table.append(thead);const tbody=el('tbody');
      for(const m of members){const tr=el('tr');tr.append(el('th',m.name));for(const d of days){const td=el('td'),slots=daySlots(m.id,d),cap=capacityLabel(m.id,d,slots);cap.classList.add('week-cap');td.append(cap);for(const s of slots)td.append(taskCard(s,true));if(state.boot.can_manage_team||m.id===state.boot.user_id){const add=el('button','+ Impegno','week-add');add.onclick=()=>openSlot(m.id,d);td.append(add);const avail=el('button','Disponibilità','week-add');avail.onclick=()=>openCapacity(m.id,d);td.append(avail);}tr.append(td);}tbody.append(tr);}table.append(tbody);wrap.append(table);board.append(wrap);
    }else for(const m of members){const section=el('section'),head=el('div',undefined,'person-head'),slots=daySlots(m.id,state.day);head.append(el('h3',m.name));const p=el('p');p.append(capacityLabel(m.id,state.day,slots));head.append(p);if(state.boot.can_manage_team||m.id===state.boot.user_id){const b=el('button','Disponibilità');b.onclick=()=>openCapacity(m.id,state.day);head.append(b);}section.append(head);if(!slots.length)section.append(el('p','Nessun impegno pianificato','empty'));for(const slot of slots)section.append(taskCard(slot));board.append(section);}
    if(!state.boot.projects.some(p=>p.enabled))$('notice').textContent='Nessun progetto abilitato. Un amministratore può scegliere i progetti da inserire nell’agenda.';
  }
  function option(select,value,text){const o=el('option',text);o.value=value;select.append(o);}
  function resetForm(form){form.querySelector('.form-error').textContent='';}
  async function submit(form,action){resetForm(form);const buttons=[...form.querySelectorAll('button')];const disabled=buttons.map(b=>b.disabled);buttons.forEach(b=>b.disabled=true);try{await action();}catch(e){form.querySelector('.form-error').textContent=errorText(e);}finally{buttons.forEach((b,i)=>b.disabled=disabled[i]);}}
  function fillPeople(selected){const project=state.boot.projects.find(p=>p.id===$('slot-project').value);$('slot-person').replaceChildren();for(const m of state.boot.members.filter(m=>project?.member_ids.includes(m.id)&&(state.boot.can_manage_team||m.id===state.boot.user_id)))option($('slot-person'),m.id,m.name);if(selected&&[...$('slot-person').options].some(o=>o.value===selected))$('slot-person').value=selected;}
  async function search(more=false){try{if(!more){state.issues=[];state.nextOffset=null;$('slot-issue').replaceChildren();}if(!$('slot-project').value)return;const data=await api('work-items/?'+new URLSearchParams({project_id:$('slot-project').value,query:$('slot-query').value,offset:more?state.nextOffset:0,limit:60}));state.issues.push(...data.results);for(const i of data.results)option($('slot-issue'),i.id,i.identifier+' · '+i.name);state.nextOffset=data.next_offset;$('more').hidden=data.next_offset==null;$('search-count').textContent=state.issues.length+' / '+data.total+' task';}catch(e){$('slot-form').querySelector('.form-error').textContent=errorText(e);}}
  async function openSlot(person=state.boot.user_id,day=state.day,source=null){
    resetForm($('slot-form'));state.createId=newId();state.reschedule=source;$('slot-form').reset();$('slot-heading').textContent=source?'Ripianifica impegno':'Pianifica attività';$('slot-day').value=day;$('slot-project').replaceChildren();for(const p of state.boot.projects.filter(p=>p.enabled))option($('slot-project'),p.id,p.name);if(source)$('slot-project').value=source.issue.project_id;fillPeople(person);for(const id of ['slot-project','slot-query','slot-person','search','slot-issue'])$(id).disabled=!!source;$('slot-dialog').showModal();
    if(source){state.issues=[source.issue];$('slot-issue').replaceChildren();option($('slot-issue'),source.issue.id,source.issue.identifier+' · '+source.issue.name);$('slot-minutes').value=source.minutes;$('slot-position').value=source.position;$('slot-outcome').value=source.outcome;$('more').hidden=true;$('search-count').textContent='';}else await search();
  }
  async function openDetail(slot){try{state.detail=await api('slots/'+slot.id+'/');const s=state.detail;resetForm($('detail-form'));resetForm($('comment-form'));$('detail-project').textContent=s.issue.project+' · '+s.issue.identifier;$('detail-title').textContent=s.issue.name;$('detail-link').href='/'+encodeURIComponent(slug)+'/browse/'+encodeURIComponent(s.issue.identifier)+'/';$('detail-meta').textContent=personName(s.person_id)+' · '+displayDate(s.day)+' · Task: '+(s.issue.state||'')+' · Scadenza: '+(s.issue.target_date?displayDate(s.issue.target_date):'non indicata');$('detail-status').value=s.status==='rescheduled'?'cancelled':s.status;$('detail-minutes').value=s.minutes;$('detail-position').value=s.position;$('detail-outcome').value=s.outcome;$('detail-blocker').value=s.blocker;const editable=(state.boot.can_manage_team||s.person_id===state.boot.user_id)&&s.status!=='rescheduled';$('detail-form').querySelectorAll('input,textarea,select,button').forEach(e=>e.disabled=!editable);$('reschedule').hidden=['done','cancelled','rescheduled'].includes(s.status);$('comment-text').value='';$('detail-dialog').showModal();await loadComments();}catch(e){showError(e);}}
  function commentPath(){const i=state.detail.issue;return '/api/workspaces/'+encodeURIComponent(slug)+'/projects/'+i.project_id+'/issues/'+i.id+'/comments/';}
  function plain(html){const t=document.createElement('template');t.innerHTML=html||'';return t.content.textContent||'';}
  async function loadComments(more=false){try{if(!more){$('comments').replaceChildren();state.commentCursor=null;}const data=await api(commentPath()+'?'+new URLSearchParams({per_page:25,...(more?{cursor:state.commentCursor}:{})}));const rows=Array.isArray(data)?data:data.results||[];for(const c of rows){const box=el('div',undefined,'comment');const actor=typeof c.actor==='object'?c.actor?.id:c.actor;box.append(el('div',(state.boot.members.find(m=>m.id===actor)?.name||'Commento')+' · '+new Date(c.created_at).toLocaleString('it-IT'),'meta'),el('div',plain(c.comment_html||c.comment_stripped||'')));$('comments').append(box);}if(!rows.length&&!more)$('comments').append(el('p','Nessun commento','muted'));state.commentCursor=data.next_page_results?data.next_cursor:null;$('more-comments').hidden=!state.commentCursor;}catch(e){$('comments').replaceChildren(el('p',errorText(e),'form-error'));}}
  async function loadCarry(){try{state.carry=await all('slots/',{...range(),carryover:'true',...(state.view==='me'?{person_id:state.boot.user_id}:{})});$('carry-list').replaceChildren();$('carry-count').textContent='('+state.carry.length+')';for(const s of state.carry){const card=taskCard(s);card.prepend(el('span',personName(s.person_id)+' · '+displayDate(s.day),'meta'));$('carry-list').append(card);}if(!state.carry.length)$('carry-list').append(el('p','Nessun impegno precedente aperto','muted'));}catch(e){showError(e);}}
  function openCapacity(person,day){state.capacityPerson=person;resetForm($('capacity-form'));$('capacity-person').textContent=personName(person);$('capacity-day').value=day;$('capacity-minutes').value=capacity(person,day)?.minutes??'';$('capacity-dialog').showModal();}
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;refresh();});
  $('day').onchange=()=>{if($('day').value){state.day=$('day').value;refresh();}};
  for(const [id,delta]of [['previous',-1],['next',1]])$(id).onclick=()=>{state.day=shift(state.day,delta*(state.view==='week'?7:1));$('day').value=state.day;refresh();};
  $('today').onclick=()=>{state.day=state.boot.today;$('day').value=state.day;refresh();};$('refresh').onclick=refresh;$('add').onclick=()=>openSlot();$('search').onclick=()=>search();$('more').onclick=()=>search(true);$('slot-project').onchange=()=>{fillPeople();search();};$('carryover').ontoggle=()=>{if($('carryover').open)loadCarry();};$('more-comments').onclick=()=>loadComments(true);
  $('slot-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const s=state.reschedule;const payload={id:state.createId,issue_id:$('slot-issue').value,person_id:$('slot-person').value,day:$('slot-day').value,minutes:Number($('slot-minutes').value),position:Number($('slot-position').value),outcome:$('slot-outcome').value,...(s?{reschedule_from:s.id,source_version:s.version}:{})};await api('slots/',{method:'POST',body:JSON.stringify(payload)});$('slot-dialog').close();await refresh();});};
  $('detail-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const s=state.detail;await api('slots/'+s.id+'/',{method:'PATCH',body:JSON.stringify({version:s.version,status:$('detail-status').value,minutes:Number($('detail-minutes').value),position:Number($('detail-position').value),outcome:$('detail-outcome').value,blocker:$('detail-blocker').value})});$('detail-dialog').close();await refresh();});};
  $('reschedule').onclick=()=>{const s=state.detail;$('detail-dialog').close();openSlot(s.person_id,shift(s.day,1),s);};
  $('comment-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const escaped=el('div',$('comment-text').value).innerHTML;await api(commentPath(),{method:'POST',body:JSON.stringify({comment_html:'<p>'+escaped.replace(/\n/g,'<br>')+'</p>'})});$('comment-text').value='';await loadComments();});};
  $('capacity-day').onchange=()=>{$('capacity-minutes').value=capacity(state.capacityPerson,$('capacity-day').value)?.minutes??'';};
  $('capacity-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{const day=$('capacity-day').value,person=state.capacityPerson;await api('capacities/',{method:'PATCH',body:JSON.stringify({person_id:person,day,minutes:Number($('capacity-minutes').value),version:capacity(person,day)?.version??0})});$('capacity-dialog').close();await refresh();});};
  $('projects-button').onclick=()=>{resetForm($('projects-form'));$('project-checks').replaceChildren();for(const p of state.boot.projects){const row=el('div',undefined,'project-check'),label=el('label'),input=el('input');input.type='checkbox';input.value=p.id;input.checked=p.enabled;label.append(input,el('span',p.name));row.append(label);$('project-checks').append(row);}$('projects-dialog').showModal();};
  $('projects-form').onsubmit=e=>{e.preventDefault();submit(e.target,async()=>{for(const input of $('project-checks').querySelectorAll('input')){const p=state.boot.projects.find(p=>p.id===input.value);if(p.enabled!==input.checked){await api('projects/'+p.id+'/',{method:'PATCH',body:JSON.stringify({enabled:input.checked})});p.enabled=input.checked;}}$('projects-dialog').close();await refresh();});};
  $('back').href='/'+encodeURIComponent(slug)+'/';
  async function start(){try{state.boot=await api('bootstrap/');if(state.boot.preview){const banner=el('div','ANTEPRIMA — Dati di esempio. Le modifiche qui non cambiano il gestionale ONIRO.','preview-banner');document.body.prepend(banner);}state.day=state.boot.today;$('day').value=state.day;$('identity').textContent=personName(state.boot.user_id);$('projects-button').hidden=!state.boot.can_manage_team;await refresh();}catch(e){$('loading').hidden=true;showError(e);$('add').disabled=true;}}
  start();
})();
